#!/usr/bin/sh

# shellcheck disable=SC1091
. /usr/share/terminate-notice/helpers

start_action "$(basename "$0")"

eval "$(load_config slack)"

debug Checking API endpoint is set
# shellcheck disable=SC2154
_slack_webhook="$(first_of "$SLACK_WEBHOOK" "$slack_webhook" "")"
if [ -z "$_slack_webhook" ]
then
    error 2 "$(basename "$0")" "No _slack_webhook defined"
fi

debug Checking _HOSTNAME is set
if [ -z "${_HOSTNAME}" ]
then
    error 2 "$(basename "$0")" "No _HOSTNAME defined"
fi

if [ "$VERIFY" = "1" ]
then
    echo "Action $(basename "$0") - INFO: Verified at start."
    exit 0
fi

debug Try to post the status
_POST_COUNTER=0
_POST_MESSAGE_SENT=0
until curl -f -s -X POST "${_slack_webhook}" -H "Content-Type: application/json" --data "{\"text\": \"A terminate-notice was received at ${_HOSTNAME}.\"}"
do
    _POST_COUNTER=$((_POST_COUNTER+1))
    if [ $_POST_MESSAGE_SENT -eq 0 ] && [ $_POST_COUNTER -eq 1 ]
    then
        echo "Action $(basename "$0") - WARNING: Waiting for the Slack Webhook to become available."
        _POST_MESSAGE_SENT=1
    elif [ $_POST_MESSAGE_SENT -eq 1 ] && [ $_POST_COUNTER -eq 5 ]
    then
        error 2 "$(basename "$0")" "Failed to send"
        exit 5
    fi
    sleep 2
done